name: Publish release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build with Gradle
      run: './gradlew build'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        artifacts: build/libs/*-fatjar.jar
        token: ${{ secrets.GITHUB_TOKEN }}
