name: 'Publish'
on:
  create:
    branches:
      - 'main'

jobs:
  publish:
    if: startsWith(github.repository, 'ModdingX/') # don't run in forks
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup Java'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Build'
        run: |
          ./gradlew \
          -Pversion=${{ github.ref_name }} \
          -PmoddingxUsername=${{ secrets.PUBLISH_USER }} \
          -PmoddingxPassword=${{ secrets.PUBLISH_PASSWORD }} \
          build publish
      - name: 'Upload Release'
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: build/libs/ModListCreator-${{ github.ref_name }}-fatjar.jar
          token: ${{ secrets.GITHUB_TOKEN }}
